name: CI Check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java ${{ matrix.jdk-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: actions/cache@v3.0.3
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: ${{ runner.os }}-gradlewrapper-

      - name: Cache Gradle packages
        uses: actions/cache@v3.0.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Maven cache
        uses: actions/cache@v3.0.3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for gradlew
        run: chmod +x reviews-dgs/gradlew shows-dgs/gradlew

      - name: Run checks
        run: make all
